-- Create tables used

-- PRODUCT
CREATE TABLE PRODUCT (
    PRODUCT_ID INT PRIMARY KEY,
    DESCRIPTION VARCHAR(255)
);

-- CUSTOMER
CREATE TABLE CUSTOMER (
    CUST_ID INT PRIMARY KEY,
    NAME VARCHAR(100),
    ADDRESS VARCHAR(255)
);

-- CUSTOMER_SALE
CREATE TABLE CUSTOMER_SALE (
    SALES_ID INT PRIMARY KEY,
    CUST_ID INT,
    FOREIGN KEY (CUST_ID) REFERENCES CUSTOMER(CUST_ID)
);

-- SALE_ITEM (tabla puente entre SALE y PRODUCT)
CREATE TABLE SALE_ITEM (
    SALES_ID INT,
    PRODUCT_ID INT,
    PRIMARY KEY (SALES_ID, PRODUCT_ID),
    FOREIGN KEY (SALES_ID) REFERENCES CUSTOMER_SALE(SALES_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
);

-- PET_CARE_LOG
CREATE TABLE PET_CARE_LOG (
    PRODUCT_ID INT,
    LOG_DATETIME TIMESTAMP,
    COMMENTS VARCHAR(255),
    PRIMARY KEY (PRODUCT_ID, LOG_DATETIME),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
);